In [ ]:
'''
imagine  yourself as a bank analyst have to figure out the reason why ppl are leaving your bank
'''

In [4]:
pip install tensorflow

     -------------------------------------- 300.8/300.8 MB 3.3 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 5.4 MB/s eta 0:00:00
     -------------------------------------- 442.0/442.0 kB 5.5 MB/s eta 0:00:00
     -------------------------------------- 413.4/413.4 kB 4.3 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 5.4 MB/s eta 0:00:00
     -------------------------------------- 130.2/130.2 kB 3.9 MB/s eta 0:00:00
     ---------------------------------------- 15.8/15.8 MB 5.5 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 5.4 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 4.6 MB/s eta 0:00:00
     -------------------------------------- 938.4/938.4 kB 4.2 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
scipy 1.9.1 requires numpy<1.25.0,>=1.18.5, but you have numpy 1.26.2 which is incompatible.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.26.2 which is incompatible.
mysql-connector-python 8.0.31 requires protobuf<=3.20.1,>=3.11.0, but you have protobuf 4.23.4 which is incompatible.


  Using cached tensorflow-2.15.0-cp39-cp39-win_amd64.whl (2.1 kB)
  Using cached tensorflow_intel-2.15.0-cp39-cp39-win_amd64.whl (300.8 MB)
  Using cached absl_py-2.0.0-py3-none-any.whl (130 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached gast-0.5.4-py3-none-any.whl (19 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached keras-2.15.0-py3-none-any.whl (1.7 MB)
  Using cached tensorboard-2.15.1-py3-none-any.whl (5.5 MB)
  Using cached ml_dtypes-0.2.0-cp39-cp39-win_amd64.whl (938 kB)
  Using cached grpcio-1.60.0-cp39-cp39-win_amd64.whl (3.7 MB)
  Using cached google_auth-2.25.2-py2.py3-none-any.whl (184 kB)
  Using cached google_auth_oauthlib-1.2.0-py2.py3-none-any.whl (24 kB)
  Using cached cachetools-5.3.2-py3-none-any.whl (9.3 kB)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
  Using cached tensorflow-2.15.0-cp39-cp39-win_amd64.whl (2.1 kB)
  Using ca

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf


RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe

SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

In [7]:
pip install --upgrade numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Users\Rejijose\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [ ]:
'''
PART 1 :DATA PREPROCESSING
'''

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [3]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
'''
Encoding Categorical Data-Gender
'''

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [6]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
'''
Encoding Categorical Data-Geography
:one Hot encoder
'''

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
'''
FEATURE SCALING
'''

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
'''
Part 2-BUILDING THE ANN
'''

In [ ]:
'''
Initializing the ann
'''

In [12]:
ann=tf.keras.models.Sequential()

In [ ]:
'''
ADDING I/P LAYER AND FIRST HIDDEN LAYER
'''

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
'''
ADDING  SECOND HIDDEN LAYER
'''

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
'''
ADDING  OUTPUT LAYER
'''

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
'''
TRAINING THE ANN
'''

In [ ]:
#compiling the ANN

In [17]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#training the ANN on training set

In [18]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100


235/235 [==============================] - 2s 2ms/step - loss: 0.6132 - accuracy: 0.7025
Epoch 2/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4994 - accuracy: 0.7963
Epoch 3/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4595 - accuracy: 0.7971
Epoch 4/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4443 - accuracy: 0.7992
Epoch 5/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4357 - accuracy: 0.8031
Epoch 6/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4301 - accuracy: 0.8093
Epoch 7/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4257 - accuracy: 0.8144
Epoch 8/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4223 - accuracy: 0.8168
Epoch 9/100
235/235 [==============================] - 1s 2ms/step - loss: 0.4190 - accuracy: 0.8207
Epoch 10/100
235/235 [==============================] - 1s 2ms/step - loss: 0.4162 - accu

235/235 [==============================] - 1s 4ms/step - loss: 0.3398 - accuracy: 0.8615
Epoch 77/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3397 - accuracy: 0.8621
Epoch 78/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3398 - accuracy: 0.8615
Epoch 79/100
235/235 [==============================] - 1s 2ms/step - loss: 0.3401 - accuracy: 0.8620
Epoch 80/100
235/235 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8611
Epoch 81/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3389 - accuracy: 0.8627
Epoch 82/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3391 - accuracy: 0.8617
Epoch 83/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3387 - accuracy: 0.8620
Epoch 84/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3390 - accuracy: 0.8615
Epoch 85/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3385 - accuracy: 

In [ ]:
'''
PART 4-MAKING PREDICTIONS AND EVALUATING THE MODEL
'''

In [ ]:
#predicting the result of single observation

In [20]:
ann.predict(sc.transform([[1,123,123,500,1,40,3,60000,2,1,1,50000]]))

1/1 [==============================] - 0s 23ms/step


array([[0.]], dtype=float32)

In [21]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

79/79 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1891  100]
 [ 247  262]]


0.8612

In [23]:
ann.predict(sc.transform([[1,123,123,600,1,40,3,60000,2,1,1,50000]]))

1/1 [==============================] - 0s 30ms/step


array([[0.]], dtype=float32)